In [14]:

import requests
import pandas as pd
import numpy as np
import pyarrow
import os
import sys
import json
import urllib.request

In [2]:
df = pd.read_parquet('../result/cp/dynamic/archived_orders/cpDynamic_orders_20240501_20240515.parquet')
df

,date,trackingCode,subId,subParam,addtag,ctag,orderId,productId,productName,quantity,gmv,commissionRate,commission,click_time
0,20240501,AF3155932,homecoin,061a7c2a-2d84-411f-9d0d-0ff82a51555a,460,7646299417,8084945774893014,1162842160,동서 옥수수차,1,14420.0,5.25,758.0,2024-05-01 22:39
1,20240501,AF3155932,homecoin,95a0bb2a-6ffc-4a16-9380-756e133bcaf3,460,7711083951,8694941974216731,6822184705,농심 인디안밥,3,2980.0,5.25,157.0,2024-05-01 14:37
2,20240501,AF3155932,homecoin,d37c2db2-8c68-414f-a2c2-f1a684502778,400,1976267316,8814944474613677,1730791677,곰곰 통밀 식빵,1,3050.0,5.25,161.0,2024-04-30 21:40
3,20240501,AF3155932,homecoin,33e43dc5-9ae0-43b6-8761-3a8f60513792,460,7757208883,8814944174249659,6854375189,한국야쿠르트 오리지널,1,8800.0,5.25,462.0,2024-05-01 17:15
4,20240501,AF3155932,homecoin,6413c766-a03c-4643-9f3d-2c4ef419180f,460,7869027269,8674940574517423,331808419,서울우유치즈 쭈욱 늘어나는 체다치즈,1,7180.0,5.25,377.0,2024-04-30 21:11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28398,20240515,AF3155932,homecoin,e8d6658f-ef49-4067-9e09-d1f84b9100e3,460,7655604119,8214940776759209,4683535861,몽베스트 생수,5,29680.0,4.50,1336.0,2024-05-14 19:23
28399,20240515,AF3155932,homecoin,9503f516-d464-45b0-be2e-369ad351fcfd,460,6743672376,8324948970354276,6468373721,비오클라쎄 밀크바오밥 베이비&키즈 페이셜 로션,1,8630.0,4.50,389.0,2024-05-15 18:19
28400,20240515,AF3155932,homecoin,73b82291-eddb-4580-aade-4d5e4202c872,460,5018558186,8604948076852067,6354913981,[로켓프레시] 델몬트 필리핀 바나나,1,4430.0,4.50,200.0,2024-05-15 15:30
28401,20240515,AF3155932,homecoin,3cd7ee8f-fe39-4a5e-941c-b9b681a69256,460,6441553801,8364941776231947,4881075720,뉴질랜드 간편단호박(슬라이스) 800g,1,10900.0,4.50,491.0,2024-05-15 15:20
28402,20240515,AF3155932,homecoin,6c1b8f72-8251-491e-9049-597c33a517d4,460,1761375156,8314942976416932,7078107918,동아오츠카 포카리스웨트,1,18780.0,4.50,846.0,2024-05-14 12:34

In [24]:
import urllib.request
import urllib.parse


encText = urllib.parse.quote("젠비타 여자 남자크로스백 슬링백 숄더백 메신저백 어깨 가방 쌕")
url = "https://openapi.naver.com/v1/search/shop?query=" + encText

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id", client_id)
request.add_header("X-Naver-Client-Secret", client_secret)

try:
    response = urllib.request.urlopen(request)
    rescode = response.getcode()
    if rescode == 200:
        response_body = response.read()
    else:
        print("Error Code:", rescode)
except urllib.error.URLError as e:
    print("URLError:", e.reason)
except urllib.error.HTTPError as e:
    print("HTTPError:", e.code)
except Exception as e:
    print("General Error:", str(e))

In [29]:
response_str = response_body.decode('utf-8')
response_json = json.loads(response_str)
items = response_json.get('items', [])
items

[]

In [27]:
response_str = response_body.decode('utf-8')

response_json = json.loads(response_str)
items = response_json.get('items', [])
items[0]['category1']
items[0]['category2']
items[0]['category3']
items[0]['category4']

IndexError: list index out of range

In [55]:
import pandas as pd
import urllib.request
import urllib.parse
import json
import time

# Sample DataFrame
# df = pd.read_parquet('path/to/your/parquet/file')


# List of client credentials
client_credentials = [

    # Add more credentials as needed
]

def search_api(client_id, client_secret, query):
    encText = urllib.parse.quote(query)
    url = "https://openapi.naver.com/v1/search/shop?query=" + encText
    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id", client_id)
    request.add_header("X-Naver-Client-Secret", client_secret)
    
    try:
        response = urllib.request.urlopen(request)
        rescode = response.getcode()
        if rescode == 200:
            response_body = response.read()
            return json.loads(response_body.decode('utf-8'))
        else:
            print("Error Code:", rescode)
            return None
    except urllib.error.HTTPError as e:
        if e.code == 429:
            print("HTTPError 429: API rate limit exceeded")
            return 429
        else:
            print("HTTPError:", e.code)
            return None
    except urllib.error.URLError as e:
        print("URLError:", e.reason)
        return None
    except Exception as e:
        print("General Error:", str(e))
        return None

# Iterate over search terms and perform API search
current_credentials = 0
results = {}
df_sp = df.sample(10)
search_terms = list(set(df_sp.productName.tolist()))

for term in search_terms:
    while True:
        client_id = client_credentials[current_credentials]["client_id"]
        client_secret = client_credentials[current_credentials]["client_secret"]
        
        result = search_api(client_id, client_secret, term)
        
        if result == 429:
            # Switch to next credentials if rate limit exceeded
            current_credentials = (current_credentials + 1) % len(client_credentials)
            if current_credentials == 0:
                # If all credentials are exhausted, wait and retry
                print("All credentials exhausted. Waiting for 60 seconds before retrying...")
                time.sleep(60)
        else:
            items = result.get('items', [])
            if len(items) > 0:
                ct1 = items[0]['category1']
                ct2 = items[0]['category2']
                ct3 = items[0]['category3']
                ct4 = items[0]['category4']
                results[term] = [ct1,ct2,ct3,ct4]
            
            else:
                results[term] = [None,None,None,None]
            
            break

pd.DataFrame(results).T

                                         0      1        2            3
써모스 마이 디자인 보틀 스트랩 원터치 텀블러 JOI-350K   생활/건강   주방용품  보관/밀폐용기       보온/보냉병
닥터스베스트 하이드롤라이즈드 케라틴 500mg 베지 캡          식품   건강식품      영양제     기타건강보조식품
오뚜기 짜슐랭                                 식품  라면/면류       라면         봉지라면
일이오 여성 하이웨스트 와이드 청바지 데님 팬츠            패션의류   여성의류      청바지
프랑프랑 플라스틱0% 에코 오리지널 65gsm 생분해 물티슈    출산/육아    물티슈       캡형
먹는샘물산수 가벼운 샘 무라벨                        식품     음료       생수
아요델 내추럴 알로에베라 선크림 SPF50+ PA+++      화장품/미용    선케어      선크림
맥심 모카골드 마일드 커피믹스                        식품     음료       커피  커피믹스/인스턴트커피
루스플로스 갸우뚱 베어 키링                       패션잡화   패션소품      키홀더
줄자(수동)_H25-55BL 5.5M, 단품             생활/건강     공구     측정공구       워킹자/줄자

In [46]:
tst = {}

tst['a'] = [1,2,3]
tst['b'] = [9,9,9]
tst['c'] = [None,None,None]
tst

{'a': [1, 2, 3], 'b': [9, 9, 9], 'c': [None, None, None]}

In [48]:
pd.DataFrame(tst)

   a  b     c
0  1  9  None
1  2  9  None
2  3  9  None

18248

In [23]:
df[['productName']].drop_duplicates()

                              productName
0                                 동서 옥수수차
1                                 농심 인디안밥
2                                곰곰 통밀 식빵
3                             한국야쿠르트 오리지널
4                     서울우유치즈 쭈욱 늘어나는 체다치즈
...                                   ...
28392              [로켓프레시] 스타벅스 스무스 아메리카노
28393                제스퍼 져키 애견간식 닭고기 400g
28394                  루이프레 유기농 홀그레인 머스타드
28396  젠비타 여자 남자크로스백 슬링백 숄더백 메신저백 어깨 가방 쌕
28399           비오클라쎄 밀크바오밥 베이비&키즈 페이셜 로션

[18248 rows x 1 columns]